package examples.hybrid.api.http

import javax.ws.rs.Path

import akka.actor.{ActorRef, ActorRefFactory}
import akka.http.scaladsl.server.Route
import examples.hybrid.blocks.{HybridBlock, PosBlock, PowBlock}
import io.circe.syntax._
import io.swagger.annotations._
import scorex.core.settings.Settings
import scorex.crypto.encode.Base58

import scala.concurrent.ExecutionContext.Implicits.global


@Path("/debug")
@Api(value = "/debug", description = "Useful functions", position = 3, produces = "application/json")
case class DebugApiRoute(override val settings: Settings, nodeViewHolderRef: ActorRef)
                        (implicit val context: ActorRefFactory) extends ApiRouteWithView {

  override val route = pathPrefix("debug") {
    infoRoute ~ chain ~ delay ~ myblocks
  }

  @Path("/delay/{id}/{blockNum}")
  @ApiOperation(value = "Average delay",
    notes = "Average delay in milliseconds between last $blockNum blocks starting from block with $id", httpMethod = "GET")
  @ApiImplicitParams(Array(
    new ApiImplicitParam(name = "id", value = "Base58-encoded id", required = true, dataType = "string", paramType = "path"),
    new ApiImplicitParam(name = "blockNum", value = "Number of blocks to count delay", required = true, dataType = "string", paramType = "path")
  ))
  def delay: Route = {
    path("delay" / Segment / IntNumber) { case (encodedSignature, count) =>
      getJsonRoute {
        viewAsync().map { view =>
          Map(
            "delay" -> Base58.decode(encodedSignature).flatMap(id => view.history.averageDelay(id, count))
              .map(_.toString).getOrElse("Undefined")
          ).asJson
        }
      }
    }
  }

  @Path("/info")
  @ApiOperation(value = "Info", notes = "Debug info about blockchain", httpMethod = "GET")
  @ApiResponses(Array(
    new ApiResponse(code = 200, message = "Json with debug info or error")
  ))
  def infoRoute: Route = path("info") {
    getJsonRoute {
      viewAsync().map { view =>
        Map(
          "height" -> view.history.height.toString.asJson,
          "bestPoS" -> Base58.encode(view.history.bestPosId).asJson,
          "bestPoW" -> Base58.encode(view.history.bestPowId).asJson,
          "bestBlock" -> view.history.bestBlock.json,
          "stateVersion" -> Base58.encode(view.state.version).asJson
        ).asJson
      }
    }
  }

  @Path("/myblocks")
  @ApiOperation(value = "Info", notes = "Blocks generated by this node", httpMethod = "GET")
  @ApiResponses(Array(
    new ApiResponse(code = 200, message = "Json with my blocks or error")
  ))
  def myblocks: Route = path("myblocks") {
    getJsonRoute {
      viewAsync().map { view =>
        val pubkeys = view.vault.publicKeys
        def isMyBlock(b: HybridBlock): Boolean = b match {
          case pos: PosBlock => pubkeys.exists(_.pubKeyBytes sameElements pos.generatorBox.proposition.pubKeyBytes)
          case pow: PowBlock => pubkeys.exists(_.pubKeyBytes sameElements pow.generatorProposition.pubKeyBytes)
        }
        val ids = view.history.filter(isMyBlock)

        Map(
          "pubkeys" -> pubkeys.map(pk => Base58.encode(pk.pubKeyBytes)).asJson,
          "count" -> ids.length.asJson,
          "ids" -> ids.map(Base58.encode).asJson
        ).asJson
      }
    }
  }

  @Path("/chain")
  @ApiOperation(value = "Chain", notes = "Print full chain", httpMethod = "GET")
  @ApiResponses(Array(
    new ApiResponse(code = 200, message = "Json with peer list or error")
  ))
  def chain: Route = path("chain") {
    getJsonRoute {
      viewAsync().map { view =>
        Map(
          "history" -> view.history.toString
        ).asJson
      }
    }
  }
}